electronics_category = Category.where(name: "Electronics").first_or_create(name: "Electronics")
men_category = Category.where(name: "Men").first_or_create(name: "Men")
women_category = Category.where(name: "Women").first_or_create(name: "Women")
baby_category = Category.where(name: "Baby & Kids").first_or_create(name: "Baby & Kids")
home_category = Category.where(name: "Home & Furniture").first_or_create(name: "Home & Furniture")
beauty_category = Category.where(name: "Beauty & Health").first_or_create(name: "Beauty & Health")
grocery_category = Category.where(name: "Grocery").first_or_create(name: "Grocery")
autos_category = Category.where(name: "Autos & Vehicles").first_or_create(name: "Autos & Vehicles")

Subcategory.where(name: "Phones & Accesories", category_id: 1).first_or_create(name: "Phones & Accesories")
Subcategory.where(name: "Clothing", category_id: 2).first_or_create(name: "Clothing")
Subcategory.where(name: "Clothing", category_id: 3).first_or_create(name: "Clothing")
Subcategory.where(name: "Shoes", category_id: 4).first_or_create(name: "Shoes")
Subcategory.where(name: "Kitchen", category_id: 5).first_or_create(name: "Kitchen")
Subcategory.where(name: "Make-up", category_id: 6).first_or_create(name: "Make-up")
Subcategory.where(name: "Daily Needs", category_id: 7).first_or_create(name: "Daily Needs")
